### ISSUE TITLE
Tensorflow Version

### ISSUE THREAD

**Issue by RasoulAM** [Luca96/face-clustering#1]
Please note the TensorFlow version in the README (I had to find out the hard way) Spoiler alert: It's not TensorFlow 2.

**Comment by Luca96** [comment]
Hi.
I've developed the project using Google Collaboratory, so I've used their version, which now is `1.15.0` and will be moved soon to version `2`.

Anyway, the tensorflow version should not be an issue since I use vanilla keras code without any tensorflow-specific functions.

**Comment by RasoulAM** [comment]
I'm actually having trouble running it in TensorFlow 2. Specifically this error raises when training starts:
`TypeError: Cannot convert 1e-12 to EagerTensor of dtype int64`

**Comment by Luca96** [comment]
Have you enabled eager execution? If so try to disable it, and see what happens.

**Comment by browarsoftware** [comment]
This code runs on TF 2.1. I had to disable eager execution.
