### ISSUE TITLE
cosine_proximity

### ISSUE THREAD

**Issue by javiermunooz** [Luca96/face-clustering#4]
**While trying to run your pre-trained model via UL19_Clustering.ipynb notebook I get an error while executing this cell:**

`model = keras.models.load_model("/content/weights-FC37-MobileNetV2-0.92.hdf5", custom_objects={'loss_max': loss_max})

model.summary()`

**This is the error:**

`ValueError                                Traceback (most recent call last)

<ipython-input-30-ded23e64f9ef> in <module>()
      3     return K.max(K.abs(y_pred - y_true), axis=-1)
      4 
----> 5 model = keras.models.load_model("/content/weights-FC37-MobileNetV2-0.92.hdf5", custom_objects={'loss_max': loss_max})
      6 
      7 model.summary()

5 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    376       if obj is None:
    377         raise ValueError(
--> 378             'Unknown ' + printable_module_name + ': ' + object_name)
    379     # Classes passed by name are instantiated with no args, functions are
    380     # returned as-is.

ValueError: Unknown loss function: cosine_proximity`

Got the same error with tf.keras instead of keras. Any ideas?

**Comment by javiermunooz** [comment]
**Solved it by implementing my own cosine_similarity function:**

`def cosine_proximity(y_true, y_pred):
     dot = np.dot(y_true, y_predb)
     norma = np.linalg.norm(y_true)
     normb = np.linalg.norm(y_pred)
     cos = dot / (norma * normb)
     return cos

model = tf.keras.models.load_model("/content/weights-FC37-MobileNetV2-0.92.hdf5", custom_objects={'cosine_proximity': cosine_proximity})

model.summary()`

**Closing**

**Comment by Luca96** [comment]
Hi @javiermunooz, sorry for the late response. 
The error is due to the `cosine_proximity` function being renamed to `cosine_similarity` from tensorflow 2.
You can avoid to implement your own `cosine_proximity` and use `tf.keras.losses.cosine_similarity` instead, just as you did.
